### ISSUE TITLE
Process 3 replicates per native and IVT samples

### ISSUE THREAD

**Issue by bhargava-morampalli** [uedaLabR/nanoDoc#4]
I was wondering if there was an option to use 3 replicates per sample (both native and IVT). Should I be doing a comparison individually i.e., native_replicate 1 with IVT_replicate 1 and so on for 3 replicates.

**Comment by uedaLabR** [comment]
Sorry that there is no 3 replicate mode. so please do it individually. Thanks

**Comment by bhargava-morampalli** [comment]
Great, thanks for getting back.
