### ISSUE TITLE
Speed up the process on a larger GPU?

### ISSUE THREAD

**Issue by bhargava-morampalli** [uedaLabR/nanoDoc#7]
Hello,

I have been using the software on a gtx 1080 GPU but I want to use it on a rtx 3080 GPU. But, the requirements of the software are CUDA 10.1. Is there a way I can use it on an upgraded GPU (with CUDA 11)?
Thanks.

**Comment by uedaLabR** [comment]
I have not tested on CUDA 11, but  I  think this software works as long as tensorflow on CUDA is available.  
try upgrade tensorflow, CUDA in requirement file.

**Comment by bhargava-morampalli** [comment]
Ah, okay. Thanks, I will try it out.
